namespace Rnd.Bot.Discord.Models.Glossaries;

public enum AncorniaSkillType
{
    //War
    Bruteforce,
    Struggle,
    Blocking,
    Fortitude,
    Fencing,
    Throwing,
    Shooting,
    Riding,
    //Mist
    Alchemy,
    Magic,
    Enchantment,
    Priesthood,
    Necromancy,
    Demonology,
    Metamorphism,
    //Way
    SleightOfHand,
    Acrobatics,
    Stealth,
    Reaction,
    Tracking,
    Navigation,
    Streets,
    Survival,
    //Word
    Empathy,
    Rhetoric,
    Manipulation,
    Networking,
    Authority,
    SelfControl,
    //Lore
    Research,
    Engineering,
    Medicine,
    Nature,
    History,
    Society,
    Science,
    //Work
    Metallurgy,
    Farming,
    Mining,
    Construction,
    Craft,
    Mechanisms,
    Chemistry,
    //Art
    Jewelry,
    Culture,
    Creation,
    Inspiration,
    Performance,
    Artistry,
    
    //Todo 
    Shamanism,
}