namespace Rnd.Api.Modules.RndCore.Parameters.SkillParameters;

public enum SkillType
{
    //War
    Bruteforce,
    Struggle,
    Blocking,
    Fortitude,
    Fencing,
    Throwing,
    Shooting,
    //Mist
    Alchemy,
    Enchantment,
    Magic,
    Necromancy,
    Shamanism,
    Priesthood,
    Demonology,
    Metamorphism,
    //Way
    SleightOfHand,
    Acrobatics,
    Stealth,
    Reaction,
    Tracking,
    Navigation,
    Riding,
    Streets,
    Survival,
    //Word
    Rhetoric,
    Empathy,
    Polemics,
    Networking,
    Authority,
    SelfControl,
    //Lore
    Research,
    Medicine,
    Nature,
    History,
    Society,
    Engineering,
    Science,
    //Work
    Metallurgy,
    Farming,
    Mining,
    Construction,
    Craft,
    Mechanisms,
    Chemistry,
    //Art
    Treasures,
    Culture,
    Creation,
    Inspiration,
    Performance,
    Artistry,
}